entities:
  AppState:
    props:
      colorMode: enum(ColorMode)
      lastRecommendation: Recommendation
      lastUpdatedAt: datetime
      isOffline: boolean
    rules:
      - 'PWA 지원 — 홈 화면 추가 가능'
      - 'Mobile First 반응형'
      - 'lastUpdatedAt은 항상 표시 (날씨는 조회 시점 기준이므로)'
      - '오프라인 시 lastRecommendation 캐시 표시'
      - '새로고침 버튼으로 날씨 및 추천 갱신 가능'
      - '한국어 전용'

enums:
  ColorMode:
    values: [light, dark]
    default: light
    note: '화이트/블랙 컬러모드, 타이포그래피 위주 미니멀 디자인'
